version: "2"
services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome
    shm_size: '2gb'
    depends_on:
      - selenium-hub
    environment:
      BROWSER: chrome
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    links:
      - selenium-hub

  bdd-testng:
    image: nitinmanojkumar/selenium-docker-bdd-testng
    depends_on:
      - "chrome"
    environment:
      - BROWSER=chrome
      - SE_EVENT_BUS_HOST=selenium-hub
      - CUCUMBER_OPTIONS=classpath:features --tags @Webdriver
    volumes:
      - ./output/testng:/usr/share/udemy/target/cucumber-reports
  
  bdd-junit:
    image: nitinmanojkumar/selenium-docker-bdd-junit
    depends_on:
      - "chrome"
    environment:
      - BROWSER=chrome
      - SE_EVENT_BUS_HOST=selenium-hub
      - CUCUMBER_OPTIONS=classpath:features --tags @Webdriver
    volumes:
      - ./output/junit:/usr/share/udemy/target/cucumber-reports